---
- name: Recover existing MachineSets
  k8s_info:
    kubeconfig: '{{ kubeconfig }}'
    api_version: machine.openshift.io/v1beta1
    kind: MachineSet
    namespace: openshift-machine-api
  register: machinesets

- name: Recover important variables from existing MachineSets
  set_fact:
    cluster_id: '{{ (machinesets.resources|first).metadata.labels["machine.openshift.io/cluster-api-cluster"] }}'
    ocs_machineset_provider_kind: '{{ (machinesets.resources|first).spec.template.spec.providerSpec.value.kind }}'
    ocs_machineset_names: '{{ machinesets.resources[0:3] | json_query("[].metadata.name") | map("regex_replace", "worker", "ocs-worker") | list }}'
    ocs_machineset_provider_specs: '{{ machinesets.resources[0:3] | json_query("[].spec.template.spec.providerSpec") }}'

- name: Swap in sizes for OCS MachineSet provider spec based on platform
  set_fact:
    ocs_machineset_provider_specs: '{{ ocs_machineset_provider_specs | map("combine", instance_type, recursive=True) | list }}'
  vars:
    instance_type:
      value:
        instanceType: '{{ ocs_node_type_mapping[ocs_machineset_provider_kind] }}'

- name: Deploy new machinesets for OCS workers
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "ocs-machinesets.yml.j2")|from_yaml }}'
