---
- name: Install OpenShift on AWS
  shell: |
    ./openshift-install create cluster
  args:
    chdir: '{{ tmp_dir }}'
    creates: '{{ kubeconfig }}'
  environment:
    AWS_ACCESS_KEY_ID: '{{ AWS_ACCESS_KEY_ID|default(ansible_env["AWS_ACCESS_KEY_ID"]) }}'
    AWS_SECRET_ACCESS_KEY: '{{ AWS_SECRET_ACCESS_KEY|default(ansible_env["AWS_SECRET_ACCESS_KEY"]) }}'
  register: installer_run

- name: Backup original kubeconfig
  copy:
    src: '{{ kubeconfig }}'
    dsg: '{{ kubeconfig }}_ORIGINAL'
  when: installer_run.changed
