---
- hosts: localhost
  collections:
    - community.kubernetes
    - community.general

  pre_tasks:
    - name: Look for default defined cluster variables
      include_vars: ../vars/cluster.yml
      when: cluster_included is not defined or not cluster_included

    - fail:
        msg: Unable to continue without cluster variables set
      when: cluster_included is not defined or not cluster_included

    - name: Set AWS_ACCESS_KEY_ID
      block:
      - pause:
          prompt: Enter your AWS Administrator account Access Key ID
        register: AWS_ACCESS_KEY_ID_tmp
      - set_fact:
          AWS_ACCESS_KEY_ID: '{{ AWS_ACCESS_KEY_ID_tmp.user_input }}'
      when: ('AWS_ACCESS_KEY_ID' not in ansible_env.keys())

    - name: Set AWS_SECRET_ACCESS_KEY
      block:
      - pause:
          prompt: Enter your AWS Administrator account Access Key Secret
        register: AWS_SECRET_ACCESS_KEY_tmp
      - set_fact:
          AWS_SECRET_ACCESS_KEY: '{{ AWS_SECRET_ACCESS_KEY_tmp.user_input }}'
      when: ('AWS_SECRET_ACCESS_KEY' not in ansible_env.keys())

  tasks:
    - include_role:
        name: openshift-installer
      when:
      - deploy_cluster|default(true)
      - cluster_name != "crc"
    - include_role:
        name: cluster-adjuster
    - include_role:
        name: redhatgov-catalog
    - include_role:
        name: ocs
      when:
      - deploy_ocs|default(true)
      - cluster_name != "crc"
